include ../config.mk
PLATFORM = 6809
CC = m6809-unknown-gcc
ASM = m6809-unknown-as
AR = m6809-unknown-ar
LINKER = m6809-unknown-ld
CFLAGS = -I$(FUZIX_DIR)/Library/include -I$(FUZIX_DIR)/Library/include/6809
LINKER_OPT = --oformat=raw -L$(FUZIX_DIR)/Library/libs -lc6809
LIBGCCDIR = $(dir $(shell $(CC) -print-libgcc-file-name))
LINKER_OPT += -L$(LIBGCCDIR) -lgcc
LINKER_OPT += --script=$(FUZIX_DIR)/Applications/util/$(TARGET).link
ASM_OPT = -o
CRT0 = $(FUZIX_DIR)/Library/libs/crt0_6809.o

.SUFFIXES: .c .o


SRCS  = decb.c detoken.c

OBJS = $(SRCS:.c=.o)

APPS = $(OBJS:.o=)

all: $(APPS) size.report

$(APPS): $(CRT0)

$(APPS): %: %.o
	$(LINKER) -o $@ $(LINKER_OPT) $^

size.report: $(APPS)
	ls -l $^ > $@

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin size.report

rmbak:
	rm -f *~ core

linux:
	gcc detoken.c -o detoken
	gcc decb.c -o decb

install:
	$(UCP) $(FSIMG) < install.ucp