include ../config.mk
PLATFORM = 6809
CC = m6809-unknown-gcc
ASM = m6809-unknown-as
AR = m6809-unknown-ar
LINKER = m6809-unknown-ld
CFLAGS = -I$(FUZIX_DIR)/Library/include -I$(FUZIX_DIR)/Library/include/6809
LINKER_OPT = --oformat=raw -L$(FUZIX_DIR)/Library/libs -lc6809 
LIBGCCDIR = $(dir $(shell $(CC) -print-libgcc-file-name))
LINKER_OPT += -L$(LIBGCCDIR) -lgcc 
LINKER_OPT += --script=$(FUZIX_DIR)/Applications/util/$(TARGET).link
ASM_OPT = -o
CRT0 = $(FUZIX_DIR)/Library/libs/crt0_6809.o

.SUFFIXES: .c .o

SRCS  = firc.c gethostbyname.c

OBJS = $(SRCS:.c=.o)

APPS = firc

all: $(APPS)

firc: $(OBJS)
	$(LINKER) $(LINKER_OPT) -o firc $(CRT0) $(OBJS)

clean:
	rm -f $(OBJS) $(APPS) $(SRCS:.c=) core *~ *.asm *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *.bin *~

rmbak:
	rm -f *~ core

install:
	$(UCP) $(FSIMG) < install.ucp